# Generated by Django 5.1.4 on 2025-01-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_armed', models.BooleanField(default=False)),
            ],
        ),
    ]
