# Generated by Django 5.1.4 on 2025-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_system', '0002_alarmsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsettings',
            name='arming_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='is_arming',
            field=models.BooleanField(default=False),
        ),
    ]
